### ISSUE TITLE
Изменение времени постройки

### ISSUE THREAD

**Issue by TheLexDev** [TheLexDev/wog3_fortifications#3]
Изменить время постройки для каждого объекта.

**Comment by StDIABLO** [comment]
Время постройки можно высчитывать по коэффициентам размера объекта.
https://community.bistudio.com/wiki/boundingBox
Типа формулы
время постройки в секундах = 30 * K 
где к - коэффициент насколько большой объект
для стандартных песочных укреплений  = 1
для небольших объектов - меньше, для больших больше

**Comment by TheLexDev** [comment]
Я не думаю, что стоит так заморачиваться над расчетом времени. Достаточно примерно прописать время для каждого объекта в зависимости от его размера.

**Comment by StDIABLO** [comment]
А вчем проблема то. Умножаешь x* y* z получаешь цифру, потом умножаешь на константу времени получаешь время на постройку в зависимости от величины объекта. Минимум счета, максимум результата.

**Comment by TheLexDev** [comment]
Предварительная корректировка времени [Таблица](https://docs.google.com/spreadsheets/d/1Alym5v2ZzEv5_ke-WsEXCKW5Gy_XhNtCzY7Jqu_yEAk/edit#gid=0)
